matrix:
  include:
    - os: linux
      language: cpp
      compiler: gcc
      sudo: required
      env:
        - ARCH=arm
        - ARM_DIR=/tmp/arm-chroot
        - PREPEND_CMD="sudo chroot $ARM_DIR"
    - os: linux
      language: cpp
      compiler: gcc
      sudo: required
    - os: osx
      language: cpp
      compiler: clang
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis_ubuntu_install.bash ; fi
  - if [[ "$ARCH" == "arm" ]]; then ./travis_setup_arm.bash $ARM_DIR ; fi
  - $PREPEND_CMD uname -a
script:
  - if [[ "$ARCH" == "arm" ]]; then $PREPEND_CMD bash -c "cd $TRAVIS_BUILD_DIR && ./build_script.bash" ; echo top ; else ./build_script.bash ; fi
