matric:
  include:
    - os: linux
      sudo: required
    - os: osx
install: if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis_ubuntu_install.bash ; fi
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_FLAGS="-std=c++11" ..
  - make
  - ./data_layout_study
