matrix:
  include:
    - os: linux
      language: cpp
      compiler: gcc
      sudo: required
      env:
        - ARCH=arm
    - os: linux
      language: cpp
      compiler: gcc
      sudo: required
    - os: osx
      language: cpp
      compiler: clang
before_install:
  - uname -p
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis_ubuntu_install.bash ; fi
  - if [[ "${ARCH}" = "arm" ]]; then ./setup_arm.bash ; fi
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_FLAGS="-std=c++11" ..
  - make
  - ./data_layout_study
