matrix:
  include:
    - os: linux
      language: cpp
      compiler: gcc
      sudo: required
      env:
        - ARCH=arm
        - ARM_DIR=/tmp/arm-chroot
    - os: linux
      language: cpp
      compiler: gcc
      sudo: required
    - os: osx
      language: cpp
      compiler: clang
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis_ubuntu_install.bash ; fi
  - if [[ "${ARCH}" = "arm" ]]; then ./travis_setup_arm.bash $ARM_DIR ; cd $ARM_DIR ; fi
  - uname -p
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_FLAGS="-std=c++11" ..
  - make
  - ./data_layout_study
