matrix:
  include:
    - os: linux
      language: cpp
      compiler: gcc
      sudo: required
      env:
        - ARCH=arm
        - ARM_DIR=/tmp/arm-chroot
        - PREPEND_CMD="sudo chroot $ARM_DIR"
    - os: linux
      language: cpp
      compiler: gcc
      sudo: required
    - os: osx
      language: cpp
      compiler: clang
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis_ubuntu_install.bash ; fi
  - if [[ "${ARCH}" = "arm" ]]; then ./travis_setup_arm.bash $ARM_DIR ; fi
  - $PREPEND_CMD uname -p
script:
  - $PREPEND_CMD mkdir build
  - $PREPEND_CMD cd build
  - $PREPEND_CMD cmake -DCMAKE_CXX_FLAGS="-std=c++11" ..
  - $PREPEND_CMD make
  - $PREPEND_CMD ./data_layout_study
